### ISSUE TITLE
My head in a ceiling (Windows Mixed Reality)

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#25] opened 2020-07-19 21:32 UTC
I use Lenovo Explorer HMD (Windows Mixed Reality) and my head is in a ceiling. A hands with a bow is under my feets.
I tried to change a SteamVR space with a room setup app and readjust floor height to 0 or -200 cm. This will change space until i restart SteamVR. But no luck.
Only working solution for me - readjust floor height in WMR portal (Put my virtual head to the floor). After that TheDarkModVR working fine.
Seems TheDarkModVR completely ignore SteamVR space and use parameters from WMR portal (I don't know how this is possible).

If this game is a "seated experience" then maybe you need to consider the starting position (When game start) of the HMD as "zero point" to game camera.
Or add a recalibration button.

**Comment by fholger** [comment] 2020-07-19 21:59
I don't have a WMR headset to test this on, but in SteamVR, there is a "recalibrate seated position" in the menu that works fine for Index/Vive headsets. Please give that a try.

**Comment by LaoGaoBeBePao** [comment] 2020-07-19 22:35
I updated SteamVR (Previously I not have this button) and test it. Yes, "reset seated position" is working. Thanks you, now I can play.
But no one other game required this button for calibrating height. For calibrating difference between "stand" and "seated" position - yes. But not for completely disable the height of virtual space.
"Head in a ceiling" - it is not normal. Still, automatic camera position calibrating when game start will be useful.

**Comment by fholger** [comment] 2020-07-20 06:11
Perhaps you just haven't played many seated experiences? Any racing game I know (e.g. DIrt Rally, Assetto Corsa, ...) or something like Bigscreen are all seated experiences that similarly require your runtime to provide the center of the seated play space. This feature exists precisely so that games don't all have to individually implement offset and recentering :)

**Comment by fholger** [comment] 2020-07-21 20:35
I am going to close this as it "works as intended" (for now, anyway). I did add some documentation to the README and the Wiki, though.

**Closed as completed by fholger** 2020-07-21 20:35 UTC
