### ISSUE TITLE
Black alpha channel (Animated textures)

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#30] opened 2020-07-20 21:11 UTC
EDIT: FM "Accountant 1: Thieves & Heirs".
Found this problem in a room with mechanical things and the fan at a ceiling. There is a box (With lightnings at above) that have animated clock face with an arrow.
In flat TDM all in normal and in TDM-VR background of this arrow is a black square.

**Comment by fholger** [comment] 2020-07-21 01:35
In normal TDM, can you try to change the color resolution to 64bits? It's in the advanced options near Bloom... And then tell me if the problem now also shows with flat TDM?

Where can I find this spot in the mission?

**Comment by LaoGaoBeBePao** [comment] 2020-07-21 01:59
Oops! Sorry, I made a mistake. I copy-paste wrong name of the FM.
This bug in "Accountant 1: Thieves & Heirs".

>In normal TDM, can you try to change the color resolution to 64bits? It's in the advanced options near Bloom... And then tell me if the problem now also shows with flat TDM?

In normal TDM (x64 exe) all is fine.
In all modes (16/32/64bits).

>Where can I find this spot in the mission?

Just walk through the mission. This room is at the beginning (Right after sewers)  so you cannot miss it.

**Comment by fholger** [comment] 2020-07-21 15:43
Turns out this is actually a bug in upstream TDM. You *can* reproduce it in flat TDM 2.08 if you set `image_useNormalCompression 2`. This option has now become the default and only option for TDM 2.09. I've tracked the bug upstream here: https://bugs.thedarkmod.com/view.php?id=5307

I'm going to close this, as the fix will automatically get merged in the VR mod as soon as it's fixed in the base game :)

**Closed as completed by fholger** 2020-07-21 15:43 UTC
