### ISSUE TITLE
Disappearing of objects when the center of the view is behind corners

### ISSUE THREAD

**Issue by LaoGaoBeBePao** [fholger/thedarkmodvr#38] opened 2020-07-29 08:14 UTC
Found in FM "Volta 1: The Stone". As an example, if the player tries to observe the guard position, from the ladder in the corridor to the Tower (When The Stone are stolen and the player need to come back and walk pass this guard).

If I walk to a wall corner and try to see what is behind this corner, then, at some angles of view, the NPC and objects will disappear.
Seems the game is deciding what object will be rendered based on the center point between the eyes. If this point is behind this corner and only one eye should see these objects, then these objects will not render to view to this eye. 

You must block one eye and the center point of the view to replicate this bug.  It is very small "window", though.

**Comment by fholger** [comment] 2020-07-29 10:08
Can you give me an exact point in the map where this happens? Type "getviewpos" in the console and let me know the output.

Depending on what kind of visibility test is executed, this is either easy to fix, or not fixable at all.

**Comment by LaoGaoBeBePao** [comment] 2020-07-29 15:30
-325.79 3535.75 -637.75 -0.0 70.7 0.0      (Do not check this, but you maybe need to open a gate to this tower. Normally, the player does this if he wants to walk in this tower, but if you just teleport to this position a closed gate may block the view)

and
648.93 2174.82 -893.75 -0.0 97.0 0.0

Move your HMD to left-right.

>or not fixable at all.

This is bad. "Leans and corners" it is one of core game mechanics in Thief and Thief-like games.
In any other games (Shooters), it will be non-critical issue, but in The Dark Mod the player will frequently see this bug. Maybe not right now, but after a room scale implementation.

**Comment by LaoGaoBeBePao** [comment] 2020-07-29 15:42
Also, check this. Another issue in this FM. Places with some light/shadow problems:

-337 3535.75 -637.75 -0.0 -45.1 0.0                    (The same place from my message above. Partial rendering of shadows)
-405.99 792.31 -989.75 -0.0 0.0 0.0                    (Partial rendering of shadows)
1584.12 2586.34 -955.75 -0.0 -84.4 0.0                    (Partial rendering of shadows)
665.72 5750.3 -923.75 -0.0 -35.8 0.0                     (Partial rendering of shadows)
1426.47 2891.43 -555.75 0.0 -179.1 0.0                    (Move your HMD to left-right. Shadow will move with your view)
-824.14 2127.88 -893.75 -0.0 -38.6 0.0                    (Shadow is flickering. Small partial rendering of shadows, as I see)
-1440.9 1950.08 -925.75 -0.0 56.3 0.0                    (Shadow of a behind object is drawn through close object?) (Also see this in FM "The Painters Wife", as a small triangle. Do not know an exact point)

Do not check this in a flat version of the game. Maybe it's not related to a VR version only.

**Comment by fholger** [comment] 2020-08-09 11:57
I looked a bit further into it. Unfortunately, it is not quite as easy to fix as I'd hoped, but I do think I can fix the incorrect clipping of objects, or at least a majority of cases. In the meantime, there is a workaround: you can set `r_useEntityPortalCulling 0`, and that should get rid of the issue in most cases, although it may cause performance issues in some places.

For the shadows, though, I'm less optimistic. It's a scissor issue, and unfortunately I don't really understand when and why the scissors become incorrect. Disabling them would fix the issue, but the performance cost is ridiculous, so that's not an option. Might be I can fix it eventually, might be we'll just have to live with it, at least until shadow mapping becomes a viable alternative in the distant future.

**Comment by fholger** [comment] 2020-08-10 20:00
Ok, the missing objects should be fixed, I hope.

As for the shadows, after taking a closer look, I was wrong. Only the bathhouse scene is scissor-related. I added a little offset that seems to fix this particular occurrence, but there may be other edge cases, and I don't think I can really do much about it. If you do find another occurrence and it bothers you, you can set `r_useDepthBoundsTest 0` (or, more radically, `vr_useLightScissors 0`, in the upcoming release), albeit at a performance penalty.

All other shadow issues appear to be present in the core 2.08 release, as far as I can tell. This may be a regression in the mod or a longer-standing issue in the mission - I haven't really seen similar bugs in other missions. Either way, they are not VR issues, so I'm going to close this ticket. You may wish to report them to the core mod, or possibly the mission author.

**Comment by fholger** [comment] 2020-08-16 19:07
FYI, I made some further changes to the culling frustum that should, in theory, ensure more accurate culling overall. However, there's always a chance I broke something, so if you find new culling mistakes or even regressions, please let me know.

**Comment by LaoGaoBeBePao** [comment] 2020-08-17 07:37
Try to test at "-191 3535.75 -637.75 -0.0 93.8 0.0". It's the other corner in the corridor.
If I move my HMD to the right, then a light sources will disappear. The statue will be in the shadow.

**Comment by fholger** [comment] 2020-08-21 19:34
I can't seem to reproduce this. Are you sure you are not accidentally moving your head into the geometry? Because in that case, yes, light sources and other stuff can potentially disappear.

**Closed as completed** 2020-11-28 14:23 UTC
